#!/bin/sh -e
#
# $Id: install-freeamp,v 1.6.4.1 1999/10/11 04:20:00 ijr Exp $
#

prefix=/usr/local

bindir="$prefix/bin"
libdir="$prefix/lib"
fadir="$libdir/freeamp"
plugdir="$fadir/plugins"
sharedir="$prefix/share"
fathemedir="$prefix/freeamp"
themedir="$prefix/themes"
ldconf="/sbin/ldconfig"

# We could use mkdir -p, but not all unix systems' mkdir's support -p
for dir in "$bindir" "$libdir" "$fadir" "$plugdir" "$sharedir" "$fathemedir" "$themedir"; do
    if [ \! -d "$dir" ]; then
	echo "mkdir $dir"
	mkdir "$dir"
	echo "chown root $dir"
	chown root "$dir"
	echo "chmod 755 $dir"
	chmod 755 "$dir"
    fi
done

install -c -m 755 freeamp "$bindir"
for file in themes/*.*; do
    echo "install -c -o root -m 644 $file $themedir"
    install -c -o root -m 644 "$file" "$themedir"
done
for file in plugins/*.*; do
    enable=f
    case "$file" in
    	*/alsa-*.pmo)
	      if $ldconf -p | grep 'libasound\.so' > /dev/null; then
	      	enable=t
	      else
	      	enable=f
		      echo "rm -f $fadir/$file"
		      rm -f "$fadir/$file"
	      fi
	   ;;
    	*/esound-*.pmo)
	      if $ldconf -p | grep 'libesd\.so' > /dev/null; then
	      	enable=t
	      else
	      	enable=f
		      echo "rm -f $fadir/$file"
		      rm -f "$fadir/$file"
	      fi
	   ;;
      */ncurses-*.ui)
         if $ldconf -p | grep 'libncurses\.so' > /dev/null; then
            enable=t
         else
            enable=f
            rm -f "$fadir/$file"
         fi
      ;; 
	   *)
	   enable=t
	   ;;
    esac
    if [ "$enable" = t ]; then
        echo "install -c -o root -m 644 $file $plugdir"
        install -c -o root -m 644 "$file" "$plugdir"
    fi
done
